bases:
  - ../../base
  
patches:
  - target:
      kind: Deployment
      name: myapp-deployment
    patch: |-
        - op: replace
          path: /spec/replicas
          value: 1
  - target:
      kind: Service
      name: myapp-service
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30035

images:
  - name: rhxpchispi/myapp
    newTag: dev

namespace: dev