apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../../base
  
patches:
  - target:
      kind: Deployment
      name: myapp-deployment
    patch: |-
        - op: replace
          path: /spec/replicas
          value: 1
images:
  - name: rhxpchispi/myapp
    newTag: dev