bases:
  - ../../base
  
patches:
  - target:
      kind: Deployment
      name: myapp-deployment
    patch: |-
        - op: replace
          path: /spec/replicas
          value: 5
images:
  - name: rhxpchispi/myapp
    newTag: main

namespace: prod