apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deployment.yaml
  - ./nodeport.yaml 

patches:
- path: "resource-patch.yaml"
  target:
    kind: "Deployment"
    name: "myapp-deployment"

images:
  - name: rhxpchispi/myapp
    newTag: main