apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rhxpchispi/prueba-ambientes
    targetRevision: HEAD
    path: overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
